apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-ms-payments
  labels:
    app: fcg-ms-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-ms-payments
  template:
    metadata:
      labels:
        app: fcg-ms-payments
    spec:
      containers:
        - name: fcg-ms-payments
          image: 399668701651.dkr.ecr.us-east-1.amazonaws.com/fcg-payments:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Stripe__PublishableKey
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-payments-secret
                  key: Stripe__PublishableKey
            - name: Stripe__SecretKey
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-payments-secret
                  key: Stripe__SecretKey
            - name: RabbitMQ__Connection
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-payments-secret
                  key: RabbitMQ__Connection
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fcg-ms-payments-service
  labels:
    app: fcg-ms-payments
spec:
  type: LoadBalancer
  selector:
    app: fcg-ms-payments
  ports:
    - port: 8080
      targetPort: 8080
