name: CD - Deploy Docker no Amazon ECR
on:
  push:
    branches:
      - master
      
permissions:
  id-token: write  
  contents: read   
  
jobs:
  deploy:
    name: Buildar e enviar imagem para o ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login no ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build da imagem Docker
      run: |
        docker build -t fcg-payments .

    - name: Tag para o ECR
      run: |
        # docker tag fcg-payments:latest ${{ secrets.ECR_REPOSITORY }}:latest
        docker tag fcg-payments:latest ${{ secrets.ECR_REPOSITORY }}:latest
    - name: Push no ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest
        
    - name: Configurar credenciais AWS via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::399668701651:role/GitHubActionsEKSRole
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHubActionsSession
        
    - name: Configurar o kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Obter credenciais do cluster EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Debug - Testar conexão EKS
      run: |
        echo "Testando conexão com o cluster..."
        kubectl cluster-info
        kubectl get nodes   

    - name: Criar ou atualizar secrets no Kubernetes
      run: |
        kubectl create secret generic fcg-ms-payments-secret \
          --from-literal=Stripe__PublishableKey="${{ secrets.STRIPE_PUBLISHABLE_KEY }}" \
          --from-literal=Stripe__SecretKey="${{ secrets.STRIPE_SECRET_KEY }}" \
          --from-literal=RabbitMQ__Connection="${{ secrets.RABBITMQ_CONNECTION }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy
      run: |
        kubectl apply -f k8s/deployment-payments.yaml
        kubectl rollout status deployment/fcg-ms-payments --namespace default
